### ISSUE TITLE
Is this abandoned / CI broken?

### ISSUE THREAD

**Issue by oskardotglobal** [Tecnativa/docker-postgres-autoconf#16]
The CI seems to be configured to run weekly, but last pushes to both Docker Hub & GHCR were 9 months ago.

Going to the [actions log](https://github.com/Tecnativa/docker-postgres-autoconf/actions/workflows/ci.yaml) there is an error: "This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs."

This seems like a security risk, is this project abandoned?

**Comment by oskardotglobal** [comment]
For everyone facing the same concern, I've forked the repository and added Postgres 16 as well as arm64 support.
See: https://github.com/cmwedding-it/docker-postgres-autoconf

**Comment by pedrobaeza** [comment]
@josep-tecnativa can you take a look?

**Comment by bosd** [comment]
@oskardotglobal Can you open a PR for ARM support?

**Comment by oskardotglobal** [comment]
Well I did kind of rewrite the whole thing with actions matrices; this means that also all the unit tests would have to be rewritten in order for this to be testable.

**Comment by oskardotglobal** [comment]
Also, I would have to readd support for docker hub, currently the workflow only supports ghcr

**Comment by pleirb** [comment]
@oskardotglobal Is this support for Postgres 16 available in Docker Hub?

**Comment by oskardotglobal** [comment]
> @oskardotglobal Is this support for Postgres 16 available in Docker Hub?

No, but they are available on GHCR: https://github.com/cmwedding-it/docker-postgres-autoconf/pkgs/container/postgres-autoconf

**Comment by pleirb** [comment]
In my particular case I am interested in using this docker-postgres-autoconf image for postgres version 16 to set up a test with docker-copier-template.
I have made the changes to my project to use the image provided by @oskardotglobal and everything seems to work very well. It would be a great contribution to integrate these changes for those who want to take advantage of the latest versions of the database, right?
